// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Connexion directe (non poolee) : necessaire pour que les migrations
    // (DDL) passent, le pooler pgbouncer de Supabase (DATABASE_URL) n'est
    // utilise qu'a l'execution par l'app, pas par la CLI Prisma.
    url: process.env["DIRECT_URL"],
  },
});
